import { NextUIProvider } from "@nextui-org/react";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Enova",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-br">
      <body>
        <NextUIProvider>
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
